### ISSUE TITLE
travis error for concurrent tests

### ISSUE THREAD

**Issue by floweisshardt** [floweisshardt/atf#13]
```
traceback (most recent call last):
  File "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest", line 36, in <module>
    rostestmain()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/__init__.py", line 273, in rostestmain
    _main()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/rostest_main.py", line 167, in rostestmain
    results_file = xmlResultsFile(pkg, outname, is_rostest, env=env)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosunit/core.py", line 102, in xml_results_file
    raise IOError("cannot create test results directory [%s]. Please check permissions."%(test_dir))
IOError: cannot create test results directory [/home/travis/catkin_ws/build/test_results/atf_test]. Please check permissions.
```

see https://travis-ci.org/ipa-fmw/atf/builds/132988829

probably two tests are trying to create directory at the same time. --> add check if directory exists. if yes: do noting

**Comment by floweisshardt** [comment]
another failure:

```
Traceback (most recent call last):
  File "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest", line 36, in <module>
    rostestmain()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/__init__.py", line 273, in rostestmain
    _main()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/rostest_main.py", line 167, in rostestmain
    results_file = xmlResultsFile(pkg, outname, is_rostest, env=env)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosunit/core.py", line 102, in xml_results_file
    raise IOError("cannot create test results directory [%s]. Please check permissions."%(test_dir))
IOError: cannot create test results directory [/home/travis/catkin_ws/build/test_results/atf_test]. Please check permissions.
```

see https://travis-ci.org/ipa-fmw/atf/builds/134564466

**Comment by MarcSeebold** [comment]
Got the same problem. Seems to be a race condition. Verified permissions on folder/files.
Using parallel building/testing. (However, for a different project)

`Traceback (most recent call last):
  File "/opt/ros/jade/share/rostest/cmake/../../../bin/rostest", line 36, in <module>
  File "/opt/ros/jade/share/rostest/cmake/../../../bin/rostest", line 36, in <module>
        rostestmain()
rostestmain()
  File "/opt/ros/jade/lib/python2.7/dist-packages/rostest/__init__.py", line 273, in rostestmain
  File "/opt/ros/jade/lib/python2.7/dist-packages/rostest/__init__.py", line 273, in rostestmain
    _main()
  File "/opt/ros/jade/lib/python2.7/dist-packages/rostest/rostest_main.py", line 167, in rostestmain
    results_file = xmlResultsFile(pkg, outname, is_rostest, env=env)
  File "/opt/ros/jade/lib/python2.7/dist-packages/rosunit/core.py", line 102, in xml_results_file
    _main()
  File "/opt/ros/jade/lib/python2.7/dist-packages/rostest/rostest_main.py", line 167, in rostestmain
    results_file = xmlResultsFile(pkg, outname, is_rostest, env=env)
  File "/opt/ros/jade/lib/python2.7/dist-packages/rosunit/core.py", line 102, in xml_results_file
    raise IOError("cannot create test results directory [%s]. Please check permissions."%(test_dir))`

**Comment by floweisshardt** [comment]
seems to be fixed by now
